name: Deploy Laravel App

on:
  push:
    branches:
      - main   # Or 'master' depending on your branch name

jobs:
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2  # Match your Laravel PHP version

    - name: Install dependencies
      run: |
        composer install --no-progress --prefer-dist --optimize-autoloader
        cp .env.example .env
        php artisan key:generate

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /var/www/html/laravel-app  # Adjust to your project directory on EC2
          git pull origin main
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan config:cache
